name: Update

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
#  schedule:
#    - cron: 0 */1 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Set git
      run : |
        git config --global user.email "109743406+zijieKwok@users.noreply.github.com"
        git config --global user.name "zijieKwok"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./luci-app-passwall
        rm -rf ./luci-app-openclash
        
        git clone --depth=1 https://github.com/kiddin9/kwrt-packages.git ./pass
        mv ./pass/luci-app-passwall ./
        rm -rf ./pass
        
        # sed -i '9i\PKG_VERSION:=4.78-2' luci-app-passwall/Makefile
        # cp -rf flags/un.svg luci-app-passwall/root/www/luci-static/passwall/flags/

        git clone --depth=1 https://github.com/vernesong/OpenClash.git -b dev
        mv ./OpenClash/luci-app-openclash ./
        rm -rf ./OpenClash
        
    - name: Apply
      run: |
        git add .
        git commit -m "Auto Sync: $(date +%Y-%m-%d" "%H:%M)"
        git push -f 
        
